//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Patcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AddToFavoritesHS {
            get {
                object obj = ResourceManager.GetObject("AddToFavoritesHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon BATScript {
            get {
                object obj = ResourceManager.GetObject("BATScript", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///using System.Data;
        ///using System.Drawing;
        ///using System.Text;
        ///using System.Windows.Forms;
        ///using System.Reflection;
        ///
        ///namespace DefaultGUI
        ///{
        ///    static class Program
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// The main entry point for the application.
        ///        /// &lt;/summary&gt;
        ///        [STAThread]
        ///        static int Main(string[] args)
        ///        {
        ///            bool hidewindow = false;
        ///            if (args.Length &gt; 0)
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultGUI {
            get {
                return ResourceManager.GetString("DefaultGUI", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap DeleteFolderHS {
            get {
                object obj = ResourceManager.GetObject("DeleteFolderHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeleteHS {
            get {
                object obj = ResourceManager.GetObject("DeleteHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon document {
            get {
                object obj = ResourceManager.GetObject("document", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap down {
            get {
                object obj = ResourceManager.GetObject("down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon ExecutableModule {
            get {
                object obj = ResourceManager.GetObject("ExecutableModule", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon folderopen {
            get {
                object obj = ResourceManager.GetObject("folderopen", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon inifile {
            get {
                object obj = ResourceManager.GetObject("inifile", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon install {
            get {
                object obj = ResourceManager.GetObject("install", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NewFolderHS {
            get {
                object obj = ResourceManager.GetObject("NewFolderHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Patcher {
            get {
                object obj = ResourceManager.GetObject("Patcher", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public static class PatcherHelper
        ///{
        ///    public const string STR_CONNECTIONSTRING = &quot;&quot;;
        ///    public const int INT_COMMANDTIMEOUT = 0;
        ///    public const string STR_SERVICESNAMES = &quot;&quot;;
        ///    public const int INT_PREVIOUSPATCHVERSIONREQUIRED = 0;
        ///    public const int INT_PATCHVERSION = 0;
        ///    public const string STR_REGISTRYPATHPATCHVERSION = &quot;&quot;;
        ///    public const string STR_REGISTRYKEYPATCHVERSION = &quot;&quot;;
        ///    public const bool BOOL_SILENTMODULEEXECUTION = false;
        ///    public const string STR_REGISTRYINSTALLPA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PatcherHelper {
            get {
                return ResourceManager.GetString("PatcherHelper", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon SQLScript {
            get {
                object obj = ResourceManager.GetObject("SQLScript", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon UNKNOWN {
            get {
                object obj = ResourceManager.GetObject("UNKNOWN", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap up {
            get {
                object obj = ResourceManager.GetObject("up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon WSHScript {
            get {
                object obj = ResourceManager.GetObject("WSHScript", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
